### ISSUE TITLE
Beagle Bone Black cannot boot when the u-boot.img is large

### ISSUE THREAD

**Issue by wweiradio** [RobertCNelson/Bootloader-Builder#8]
Hi,

This is not an bug, but a question. Thank you for your help in advance. 

I am trying to enable the BBB to display a picture on LCD while u-boot is running before the Linux kernel is loaded.  The LCD screen is 800*480, 24 bits per pixel.  

When the image data is compiled into u-boot (total size of the compiled u-boot is 786 kB) , it cannot boot successfully. 

```
sudo dd if=MLO-am335x_boneblack-v2016.11-3-gf2fb808-r0 of=/dev/sdc count=1 seek=1 conv=notrunc bs=128k

68592 bytes (69 kB, 67 KiB) copied, 0.00140823 s, 48.7 MB/s
sudo dd if=u-boot-am335x_boneblack-v2016.11-3-gf2fb808-r0.img of=/dev/sdc count=2 seek=1 conv=notrunc bs=384k

786432 bytes (786 kB, 768 KiB) copied, 0.0011435 s, 688 MB/s
```

Just display the following from the console.  

```
U-Boot SPL 2016.11-00003-gf2fb808-dirty (Jan 01 2017 - 11:37:29)
Trying to boot from MMC1
```

A twisted image can be displayed on LCD screen when the size of the image is reduced. 
Therefore, I assume the size of the u-boot image caused the u-boot failure to boot. But I have no idea how to add debug to dig out.

Please advise how to solve the issue. I want to display the 800*480 picture.

**Comment by wweiradio** [comment]
i have found the reason: 
i was using the following command to write the u-boot.img. but for my case, two counts is not enough.
sudo dd if=$IMG of=/dev/sdc count=2 seek=1 conv=notrunc bs=384k

**Comment by laksonobudi** [comment]
i have same problem too... have u done it?

**Comment by RobertCNelson** [comment]
@laksonobudi just bump the count..

```
sudo dd if=./u-boot/MLO of=${DISK} count=1 seek=1 bs=128k
sudo dd if=./u-boot/u-boot.img of=${DISK} count=4 seek=1 bs=384k
```

**Comment by laksonobudi** [comment]
but my u-boot.img size is 1.6 mb

**Comment by laksonobudi** [comment]
i have done that but still like this... @RobertCNelson 

U-Boot SPL 2017.09-dirty (Oct 18 2017 - 10:13:12)                               
Trying to boot from MMC1                                                        
*** Warning - bad CRC, using default environment

**Comment by leomeza1** [comment]
I've got the same problem. Those three lines just keep repeating, can't boot. I used fdisk to partition my uSD card.

Disk /dev/sdb: 15.8 GB, 15836643328 bytes
66 heads, 1 sectors/track, 468650 cylinders, total 30930944 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x0003f898

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1   *        2048       67583       32768    c  W95 FAT32 (LBA)
/dev/sdb2           67584    30930943    15431680   83  Linux

**Comment by RobertCNelson** [comment]
@leomeza1 , After this problem first came out, we moved to a bigger hole at the start of the partition:

```bash
sudo sfdisk ${DISK} <<-__EOF__
4M,,L,*
__EOF__
```

https://www.digikey.com/eewiki/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-SetupmicroSDcard

From your dump, you still are using a 1MB hole..

Regards,
